# Generated by Django 3.2.8 on 2021-11-10 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_author_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='stih',
            name='checked',
            field=models.BooleanField(default=True),
        ),
    ]
