# Generated by Django 3.2.8 on 2021-11-10 10:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_stih_checked'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stih',
            old_name='checked',
            new_name='_checked',
        ),
    ]
