# Generated by Django 3.2.8 on 2021-11-10 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_rename_checked_stih__checked'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stih',
            options={'permissions': (('can_validate', 'Set stih as valid'),)},
        ),
    ]
