# Generated by Django 3.2.8 on 2021-11-15 16:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_alter_stih_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stih',
            options={'permissions': (('can_validate', 'Set stih as valid'), ('cant_validate', 'Low permissions user'))},
        ),
    ]
