# Generated by Django 3.2.8 on 2021-11-15 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_alter_stih_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stih',
            name='_checked',
            field=models.BooleanField(default=False),
        ),
    ]
